- name: RabbitMQ setup
  hosts: all
  become: true
  tasks:
    - name: download Erlang repo
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: download rabbitmq repo
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Install RabbitMQ server
      ansible.builtin.yum:
        name: rabbitmq-server
        status: installed

    - name: Start RabbitMQ Service
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: restarted
        enabled: yes

    - name: Add application user
      community.rabbitmq.rabbitmq_user:
         user: roboshop
         password: roboshop123
         vhost: /
         configure_priv: .*
         read_priv: .*
         write_priv: .*
         state: present






#rabbitmq_app_password=$1
#if [ -z "${rabbitmq_app_password}" ]; then
#echo Input Rabbitmq app user password missing
#exit 1
#fi
#curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
#curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
#yum install rabbitmq-server -y
#systemctl enable rabbitmq-server
#systemctl start rabbitmq-server
#rabbitmqctl add_user roboshop ${rabbitmq_app_password}
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"